### ISSUE TITLE
Feeds not updating

### ISSUE THREAD

**Issue by mr-bobdobalina** [wltb/ff_instagram#5] opened 2018-06-14 04:54 UTC
All of my IG subscriptions report this error when I do a manual feed refresh in TT-RSS: 

"PHP Fatal error:  Call to undefined function feed_has_icon() in /*PATH TO MY TT-RSS*/plugins.local/ff_instagram/init.php on line 40"

I have tried unsubscribing and re-subscribing to them but no change.  It actually breaks my TT-RSS feed updates altogether. I have to disable the plugin to get my feeds working again.

**Comment by wltb** [comment] 2018-06-14 09:44
Sorry for your trouble. This is a duplicate of #3, so something should be done about this. Could you please test if this code helps you:
`if(! function_exists('feed_has_icon')) {
	function feed_has_icon($arg) {return Feeds::feedHasIcon($arg);}
}`
Simply put it above the _ff_Instagram_ class in _init.php_ and report back.

**Comment by mr-bobdobalina** [comment] 2018-06-14 22:14
Looks like that did the trick. Thank you for the help and great job on this plugin!

**Closed as completed** 2018-06-14 22:14 UTC
